package com.knack.store.controller;

import com.knack.store.dto.ProductViewDTO;
import com.knack.store.service.ProductViewService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirements;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/product-views")
@RequiredArgsConstructor
@Tag(name = "Product Views", description = "Track and retrieve recently viewed products for guest users")
@SecurityRequirements
public class ProductViewController {

    private final ProductViewService productViewService;

    /**
     * Log a product view for a guest session
     * When a guest user views a product, this endpoint should be called to track the view.
     * If the product was already viewed, it moves to the front of the recently viewed list.
     *
     * POST /api/product-views/log
     * Request Body:
     * {
     *   "guestSessionId": "uuid-generated-by-frontend",
     *   "productId": 1
     * }
     */
    @PostMapping("/log")
    @Operation(
            summary = "Log a product view",
            description = "Record that a guest user has viewed a product. If the product was already viewed, it will be moved to the front of the recently viewed list."
    )
    @ApiResponse(responseCode = "201", description = "Product view logged successfully",
            content = @Content(schema = @Schema(implementation = ProductViewDTO.LogProductViewResponse.class)))
    @ApiResponse(responseCode = "400", description = "Invalid request data")
    @ApiResponse(responseCode = "404", description = "Product not found")
    public ResponseEntity<ProductViewDTO.LogProductViewResponse> logProductView(
            @RequestBody ProductViewDTO.LogProductViewRequest request) {
        ProductViewDTO.LogProductViewResponse response = productViewService.logProductView(
                request.getGuestSessionId(),
                request.getProductId()
        );
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * Get recently viewed products for a guest session
     * Returns up to 10 most recently viewed products, ordered by most recent first.
     *
     * GET /api/product-views/recently-viewed?guestSessionId=uuid-from-frontend
     */
    @GetMapping("/recently-viewed")
    @Operation(
            summary = "Get recently viewed products",
            description = "Retrieve up to 10 most recently viewed products for a guest session, ordered by most recent first."
    )
    @ApiResponse(responseCode = "200", description = "Recently viewed products retrieved successfully",
            content = @Content(schema = @Schema(implementation = ProductViewDTO.RecentlyViewedResponse.class)))
    @ApiResponse(responseCode = "400", description = "Missing or invalid guestSessionId")
    public ResponseEntity<ProductViewDTO.RecentlyViewedResponse> getRecentlyViewed(
            @RequestParam(name = "guestSessionId")
            @Parameter(description = "Unique guest session identifier (UUID generated by frontend)", required = true)
            String guestSessionId) {
        ProductViewDTO.RecentlyViewedResponse response = productViewService.getRecentlyViewed(guestSessionId);
        return ResponseEntity.ok(response);
    }

    /**
     * Get recently viewed products with full product details
     * Returns up to 10 most recently viewed products with complete ProductDTO information.
     * Useful when you need detailed product info (variants, ratings, etc.)
     *
     * GET /api/product-views/recently-viewed/detailed?guestSessionId=uuid-from-frontend
     */
    @GetMapping("/recently-viewed/detailed")
    @Operation(
            summary = "Get recently viewed products with details",
            description = "Retrieve up to 10 most recently viewed products with full product details including variants, ratings, and category information."
    )
    @ApiResponse(responseCode = "200", description = "Recently viewed products with details retrieved successfully")
    @ApiResponse(responseCode = "400", description = "Missing or invalid guestSessionId")
    public ResponseEntity<List<ProductViewDTO>> getRecentlyViewedWithDetails(
            @RequestParam(name = "guestSessionId")
            @Parameter(description = "Unique guest session identifier (UUID generated by frontend)", required = true)
            String guestSessionId) {
        List<ProductViewDTO> response = productViewService.getRecentlyViewedWithDetails(guestSessionId);
        return ResponseEntity.ok(response);
    }

    /**
     * Clear all recently viewed products for a guest session
     * Deletes all product view records for the specified guest session.
     *
     * DELETE /api/product-views/clear?guestSessionId=uuid-from-frontend
     */
    @DeleteMapping("/clear")
    @Operation(
            summary = "Clear recently viewed products",
            description = "Delete all recently viewed products for a guest session."
    )
    @ApiResponse(responseCode = "204", description = "Recently viewed products cleared successfully")
    @ApiResponse(responseCode = "400", description = "Missing or invalid guestSessionId")
    public ResponseEntity<Void> clearRecentlyViewed(
            @RequestParam(name = "guestSessionId")
            @Parameter(description = "Unique guest session identifier (UUID generated by frontend)", required = true)
            String guestSessionId) {
        productViewService.clearRecentlyViewed(guestSessionId);
        return ResponseEntity.noContent().build();
    }
}

